<?php
require "shared.inc";
standard_header("Repository Access");
?>

<p>The development source code for Gwydion Dylan, Open Dylan, and
collections of Dylan libraries and example code is
stored on <a href="https://github.com/dylan-lang/">github</a>.</p>

Please contact us via IRC or our mailing list if you need write
access, as described on the <a href="community.phtml">community</a> webpage.

<!-- TODO: how does cvszilla concern us these days?
<h2 id="cvszilla">Using CVSZilla</h2>

<p>We use the <a href="http://www.cvszilla.org/">CVSZilla</a> tool to
track development "threads".  CVSZilla associates each commit to the
repository with a <a
href="http://www.gwydiondylan.org/bugs/">Bugzilla</a> entry, and adds
commit log entries as comments to the associated bug(s).  The CVSZilla
database can also be <a
href="https://www.gwydiondylan.org/cvszilla/query.cgi">searched</a>
in various ways.
</p>

<p>Most development work should be preceded by the <a
href="http://www.gwydiondylan.org/bugs/enter_bug.cgi">filing</a> of a
bug or enhancement request in Bugzilla.  Small changes can be vetted
for comment by attaching patches to the bug and bringing it to the
attention of other developers.  (Larger development projects should be
associated with a branch, allowing it to be reviewed before it is
merged back to <tt>trunk/</tt>.</p>

<p>When changes are committed, the first line of the commit log must be of
the form:</p>

<pre>
Bug: <var>bug-number</var> ...
</pre>

<p>so that CVSZilla can annotate the bug(s).</p>

<p>If a commit is a one-off change (not part of a development thread)
and doesn't fix a particular bug, you can use one of the <a
href="http://www.gwydiondylan.org/cvszilla/job.cgi">general
development jobs</a>.  In this case the first line of the commit log
should look like:

<pre>
Job: <var>job-name</var> ...
</pre>
-->

<h2>Line Endings</h2>

We use unix line endings and spaces in our repository!

<?php standard_footer(); ?>
